name: Deploy Automático no Coolify

on:
  push:
    branches:
      - main # Dispara sempre que houver push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar Webhook do Coolify
        run: |
          curl -X GET "https://coolify-webhook.gabiferreiraterapeuta.com.br/api/v1/deploy?uuid=fhksz2vyg4o189o9en6nto0u&force=false" \
          -H "Authorization: Bearer 1|eokZ82530w4NcOs68ngvZp4chPo5JI3rJNRLS9rl07c45906"

